# Generated by Django 3.1.7 on 2021-06-10 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20210610_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead.userprofile'),
            preserve_default=False,
        ),
    ]
