# Generated by Django 3.1.7 on 2021-06-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_agent_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='organisation',
        ),
    ]
