# Generated by Django 3.1.7 on 2021-06-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_auto_20210612_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=True),
        ),
    ]
