# Generated by Django 3.1.7 on 2021-06-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_auto_20210612_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead.userprofile'),
            preserve_default=False,
        ),
    ]
