# Generated by Django 3.1.7 on 2021-06-17 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_auto_20210617_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lead.userprofile'),
            preserve_default=False,
        ),
    ]
